version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo-dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpass
    volumes:
      - mongo_data:/data/db
    command: mongod --auth

  mongo-express:
    image: mongo-express
    container_name: mongo-express-dev
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: devuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpass
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: e-learning-dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
  redis_data:
