{
    id: 'cs_test_a1JdCGWnGKgi7b91y3FnTfmAUpQ1DuwvWac5bI88T0OCr3P9UyVjkJkAz1',
    object: 'checkout.session',
    after_expiration: null,
    allow_promotion_codes: null,
    amount_subtotal: 100000,
    amount_total: 100000,
    automatic_tax: { enabled: false, liability: null, status: null },
    billing_address_collection: null,
    cancel_url: 'https://e-learning-api-ruddy.vercel.app/cancel',
    client_reference_id: null,
    client_secret: null,
    consent: null,
    consent_collection: null,
    created: 1727533781,
    currency: 'egp',
    currency_conversion: null,
    custom_fields: [],
    custom_text: {
      after_submit: null,
      shipping_address: null,
      submit: null,
      terms_of_service_acceptance: null
    },
    customer: null,
    customer_creation: 'if_required',
    customer_details: {
      address: {
        city: null,
        country: 'EG',
        line1: null,
        line2: null,
        postal_code: null,
        state: null
      },
      email: 'kero68@gmail.com',
      name: 'kero',
      phone: null,
      tax_exempt: 'none',
      tax_ids: []
    },
    customer_email: null,
    expires_at: 1727620181,
    invoice: null,
    invoice_creation: {
      enabled: false,
      invoice_data: {
        account_tax_ids: null,
        custom_fields: null,
        description: null,
        footer: null,
        issuer: null,
        metadata: {},
        rendering_options: null
      }
    },
    livemode: false,
    locale: null,
    metadata: {
      userId: '66e82ea882a842bdd8875b31',
      paymentId: '66f812d5615ec15c8de14ff7'
    },
    mode: 'payment',
    payment_intent: 'pi_3Q41erBexFfZ5wR3121gybqx',
    payment_link: null,
    payment_method_collection: 'if_required',
    payment_method_configuration_details: null,
    payment_method_options: { card: { request_three_d_secure: 'automatic' } },
    payment_method_types: [ 'card' ],
    payment_status: 'paid',
    phone_number_collection: { enabled: false },
    recovered_from: null,
    saved_payment_method_options: null,
    setup_intent: null,
    shipping_address_collection: null,
    shipping_cost: null,
    shipping_details: null,
    shipping_options: [],
    status: 'complete',
    submit_type: null,
    subscription: null,
    success_url: 'https://e-learning-api-ruddy.vercel.app/success?session_id={CHECKOUT_SESSION_ID}',
    total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
    ui_mode: 'hosted',
    url: null
  }