export * from './confirmDeleteQuiz.controller'
export * from './getAllQuizzes.controller'
export * from './getQuizById.controller'
export * from './updateQuiz.controller'
export * from './createQuiz.controller'
export * from './deleteQuiz.controller'